services:
  ubuntu-c1ux:
    container_name: c1ux
    build: .
    image: ubuntu-c1ux:latest
    restart: unless-stopped
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ./_temp_:/mnt/disk
      - ./RU:/mnt/RU
      - ./KZ:/mnt/KZ
      - ./4G:/mnt/4G
      - ./root/.bash_profile:/root/.bash_profile
      - ./root/.bashrc:/root/.bashrc
      - ./root/bin:/root/bin
      - ./root/etc:/root/etc
